### ISSUE TITLE
how deploy to AWS 

### ISSUE THREAD

**Issue by Wolke** [mz026/universal-redux-template#30]
really thx

**Comment by mz026** [comment]
Hi @Wolke ,
The last step to deploy to AWS would be running 
```
$ NODE_ENV=production NODE_PATH=./app node app/server
```
on a server with node environment installed. In order to do that, you want to do the following on each deployment:

1. ssh into the server and fetch the latest code from your SCM such as github or bitbucket
2. run `npm install` to make `node_module` up to date

The step above can be done manually or automatically with tool such as [Capistrano](http://capistranorb.com/) or its alternative.
