### ISSUE TITLE
Production reload

### ISSUE THREAD

**Issue by michaljarnot** [mz026/universal-redux-template#33]
How do I make production not reload when changing routes? I mean refreshing pages. When this template runs on webpack-dev-server there is this live reload that I cannot replicate on production. It kind of looses the point of react when website refreshes on every click.

**Comment by mz026** [comment]
Hi @michaljarnot ,

The route changing on front-end should go with history API (not reloading), so there must be something wrong :stuck_out_tongue: 

I guess the issue you encountered was due to the script didn't load on browser side.
Is there any error message on browser console / nodejs terminal console in development mode on your local machine?

**Comment by michaljarnot** [comment]
Thanks for answer. :) You have really cool and understandable setup. Even with tests and everything. The only thing missing is the broken refresh on production.

I should have probably asked: "how do I run production?" You have only one command for starting the project that runs app/server, then it runs webpack - do I want that? i should not use webpack-dev-server in production - and then it runs gulp.

**Comment by michaljarnot** [comment]
I think that the problem is that the app is trying to run vendor.js, app.js and dev.js from :3001. My node version is 5.7.

**Comment by michaljarnot** [comment]
Woooow I am fucking idiot. I run webpack in production mode but I forgot to run server in production mode so it tried to load the scripts from localhost. I will test it little bit more but I think I got it. Thank you so much.

**Comment by mz026** [comment]
No problem! Let me know how it goes :smile:

**Comment by michaljarnot** [comment]
OK I added into package.json:

> "start:prod": "cross-env NODE_ENV=production NODE_PATH=./app concurrently --kill-others \"webpack\" \"nodemon app/server\" \"gulp css:watch\"",

Now it works. :)

**Comment by mz026** [comment]
I don't think running `webpack` and `nodemon` in production mode is a good idea due to performance issue. (But it's find to do that on local machine as a test)

Normally you want to serve the webpack-built assets as static ones and use a process manager such as [forever](https://github.com/foreverjs/forever) to monitor the node process.

**Comment by mz026** [comment]
I'm going to close this if everything goes fine. Let me know if there's any further issue. :)
