### ISSUE TITLE
Question: Multiple server side dispatches?

### ISSUE THREAD

**Issue by bolicd** [mz026/universal-redux-template#41]
Hello,

im currently using CHAIN_API to perform multiple async loads on server side.
For example loadIntroData will perform CHAIN_API with 3 calls:
static fetchData({ store }) {
    return store.dispatch( loadIntroData('some') );
  }

Is it possible to use multiple store.dispatch calls instead of one chain api?
So something like:

static fetchData({ store }) {
   store.dispatch( loadSomething());
   store.dispatch( loadSomethingElse());
    return store.dispatch( loadIntroData('some') );
  }

Thanks

**Comment by mz026** [comment]
Hello @bolicd ,

Thanks for checking out!
`CHAIN_API` is designed for the cases in which we want to **treat successive API calls as one action**. So if the API calls do not depend on the result of each other, it's better to put them in multiple action creators and use multiple `dispatch`-es as you specified on the second code snippet.

To make it work when doing server rendering, the `fetchData` needs to return a promise to let server code know when it finishes the fetching. And since `store.dispatch` returns a promise if the action is of type `CALL_API`, we can use [`Promise.join`](http://bluebirdjs.com/docs/api/promise.join.html) to accomplish that like this:

```javascript

static fetchData({ store }) {
  return Promise.join(
    store.dispatch(loadSomething())
    store.dispatch(loadSomethingElse())
  )
}
```

**Comment by bolicd** [comment]
👍 
Thanks a lot, very clear explanation, this is what I needed.

Thank you
